version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels: []
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-patch'
          - 'version-update:semver-minor'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels: []
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-patch'
          - 'version-update:semver-minor'
